## HOME
ecommerce_homepage: #product list + ???? à déterminer
    path:     /
    defaults: { _controller: EcommerceBundle:Home:index }

ecommerce_product:
    resource: "@EcommerceBundle/Resources/config/routing/routingproduct.yml"
    prefix: /product

ecommerce_basket:
    resource: "@EcommerceBundle/Resources/config/routing/routingbasket.yml"
    prefix: /basket

ecommerce_order:
    resource: "@EcommerceBundle/Resources/config/routing/routingorder.yml"
    prefix: /order

## ADMIN - PRODUCT

ecommerce_admin_product:
    resource: "@EcommerceBundle/Resources/config/routing/routingproductAdmin.yml"
    prefix:   /admin/product