user:
    resource: "@UserBundle/Resources/config/routing/routingUser.yml"
    prefix: /user

user_dashboard:
    resource: "@UserBundle/Resources/config/routing/routingDashboard.yml"
    prefix: user/dashboard

user_address:
    resource: "@UserBundle/Resources/config/routing/routingAddress.yml"
    prefix: /address
## USER ADMIN ##
admin_user:
    resource: "@UserBundle/Resources/config/routing/admin/routingUserAdmin.yml"
    prefix: /admin/user

admin_user_address:
    resource: "@UserBundle/Resources/config/routing/admin/routingAddressAdmin.yml"
    prefix: /admin/address
