dashboard_user:
    resource: "@UserBundle/Resources/config/routing/routingDashboard.yml"
    prefix: /dashboard

admin_user:
    resource: "@UserBundle/Resources/config/routing/admin/routingUserAdmin.yml"
    prefix: /admin/user

admin_user_address:
    resource: "@UserBundle/Resources/config/routing/admin/routingAddressAdmin.yml"
    prefix: /admin/address