user_homepage:
    path:     /dashboard
    defaults: { _controller: UserBundle:User:dashboardIndex }

user_bills:
    path:     /dashboard/bills/list
    defaults: { _controller: UserBundle:User:dashboardBillsList }

user_bill:
    path:     /dashboard/bills/{orderid}
    defaults: { _controller: UserBundle:User:dashboardBillPDF }
