pageAdmin_index:
    path:     /
    defaults: { _controller: "PagesBundle:PageAdmin:index" }
    methods:  GET

pageAdmin_trash:
    path:     /trash
    defaults: { _controller: "PagesBundle:PageAdmin:trash" }
    methods:  GET

pageAdmin_restore:
    path:     /{id}/restore
    defaults: { _controller: "PagesBundle:PageAdmin:restore" }
    methods:  [GET, POST]

pageAdmin_show:
    path:     /{id}/show
    defaults: { _controller: "PagesBundle:PageAdmin:show" }
    methods:  GET

pageAdmin_show_page_version:
    path:     /{id}/{idv}/show
    defaults: { _controller: "PagesBundle:PageAdmin:showPageVersion" }
    methods:  GET

pageAdmin_revert_to_this_version:
    path:     /{id}/{idv}/revert
    defaults: { _controller: "PagesBundle:PageAdmin:revertToThisVersion" }
    methods:  [GET,POST]

pageAdmin_new:
    path:     /new
    defaults: { _controller: "PagesBundle:PageAdmin:new" }
    methods:  [GET, POST]

pageAdmin_edit:
    path:     /{id}/edit
    defaults: { _controller: "PagesBundle:PageAdmin:edit" }
    methods:  [GET, POST]

pageAdmin_delete:
    path:     /{id}/delete
    defaults: { _controller: "PagesBundle:PageAdmin:delete" }
    methods:  DELETE
