pages_pageAdmin:
    resource: "@PagesBundle/Resources/config/routing/routingPageAdmin.yml"
    prefix:   /admin/page

page_view:
    path: page/{id}
    defaults: { _controller: PagesBundle:Page:pageView }
