admin_addresses:
    path:     /
    defaults: { _controller: "UserBundle:AddressAdmin:index" }
    methods:  GET

admin_address_new:
    path:     /new
    defaults: { _controller: "UserBundle:AddressAdmin:new" }
    methods:  [GET, POST]

admin_address_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:AddressAdmin:show" }
    methods:  GET

admin_address_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:AddressAdmin:edit" }
    methods:  [GET, POST]

admin_address_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:AddressAdmin:delete" }
    methods:  [GET, DELETE]
