<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTheCategory($categId){

		return $this->createQueryBuilder('c')
					->select('c')
					->where('c.id = :id')
					->setParameter('id', $categId)
					->getQuery()->getResult();
	}

}
