<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

	public function getProductsByCategory ($categid){

		return $this->createQueryBuilder('p')
			->select('p')
			->where('p.category = :category')
			->andWhere('p.isonline = 1')
			->orderBy('p.id')
			->setParameter('category',$categid)
			->getQuery()->getResult();
	}

	public function getProductsByTermsSearched($terms){
		return $this->createQueryBuilder('p')
			->select('p')
			->where('p.name LIKE :terms') //OR p.category
			->andWhere('p.isonline = 1')
			->orderBy('p.name')
			->setParameter('terms', '%'.$terms.'%')
			->getQuery()->getResult();
	}

}
