<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * UserOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderRepository extends \Doctrine\ORM\EntityRepository
{
	public function getBillsByUser($userid){

		return $this->createQueryBuilder('o')
			->select('o')
			->where('o.user = :userid')
			->andWhere('o.valid = 1')
			->andWhere('o.ordercode != 0')
			->orderBy('o.id')
			->setParameter('userid', $userid)
			->getQuery()->getResult();
	}
}
