<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * VatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VatRepository extends \Doctrine\ORM\EntityRepository
{

}
